--- #YAML:1.0
name:                Exporter
version:             5.61
abstract:            Implements default import method for modules
license:             perl
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
