---
abstract: 'Implements default import method for modules'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.58, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exporter
no_index:
  directory:
    - t
    - inc
recommends:
  Test::Pod: 1.18
  Test::Pod::Coverage: 1.04
requires:
  Carp: 1.05
resources:
  bugtracker: http://rt.perl.org/perlbug/
  license: http://dev.perl.org/licenses/
  repository: http://perl5.git.perl.org/perl.git/tree/HEAD:/lib
  x_MailingList: http://lists.perl.org/list/perl5-porters.html
version: 5.65
